# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Запускаем стандартные утилиты
    cmds:
      - go fmt ./...
      - go vet ./...
      - go mod vendor
      - go test ./...
      - golangci-lint run -c .golangci.yaml